# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Foo Guo Sen, Jeff
title: Software Engineer
email: guosen.foo@gmail.com
website: www.github.com/jefff00/

# Social links
#twitter_username: facespics
github_username:  jefff00
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: guosen-foo
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jeff and I'm a software engineer. My experience is in Android mobile application development and have also developed small scale web projects. Starting in the industry from 2011 I have worked at a number of companies contributing my knowledge in development and also gaining technical, teamwork and leadership skills.

  I am most skilled in: <mark>Android</mark>, <mark>Java</mark>
  
  I have also worked on and am familiar with the following technologies & tools: <mark>Jenkins</mark>, <mark>Javascript</mark>, <mark>GIS</mark>, <mark>Mapbox</mark>, <mark>AWS</mark>
  
  My other skills include: <mark>unit testing</mark>, <mark>Junit</mark>, <mark>Jacoco</mark>, <mark>validation & verification</mark>, <mark>Agile software development - SCRUM</mark>

  My personal philosophy is: tools and technologies are always changing, it's better to be adaptable and embrace a learning mindset.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Apart from writing software and working on weekend projects, my interests and hobbies are:
    - basketball
    - hiking
    - making traditional desserts 糖水

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
